### ISSUE TITLE
configurable/lower sample rate for DC cal app

### ISSUE THREAD

**Issue by guruofquality** [fairwaves/UHD-Fairwaves#10]
The DC calibration app need a lower sample rate to avoid underflows on less-powerful machines. The default sample rate could be lowered or a configurable command line option could be added. A lower default for the tx stream is probably fine, as tx is just used to generate a simple tone.

**Comment by chemeris** [comment]
I actually fixed this and improved the app quite a bit. I'll check it in today hopefully.

**Comment by chemeris** [comment]
Fixed in 7b15bc857b2fae88f23c6060f4708f4a12312aad
